name: Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

concurrency:
  group: production
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nheroop/business-management-system-backend

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh

          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/github-actions
          chmod 600 ~/.ssh/github-actions

          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          ssh \
            -i ~/.ssh/github-actions \
            -p ${{ secrets.SSH_PORT }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'

          set -euxo pipefail

          cd ~/repos/Business-Management-System-Backend

          echo "Current commit:"
          git rev-parse HEAD

          git fetch origin
          git reset --hard origin/main

          echo "Updated commit:"
          git rev-parse HEAD

          docker compose pull

          docker compose up -d \
            --force-recreate \
            --remove-orphans

          docker image prune -f

          docker compose ps

          EOF